### ISSUE TITLE
No more temporary support of experiments in Firefox Developers Edition

### ISSUE THREAD

**Issue by jsperf-account** [web-ext-experiments/about#14]
Since Firefox Developers Edition 54.0b14 (32bit / Win7) this extension can't be loaded anymore temporary by using "about:debugging". This seems to be a general issue, extension type 256 isn't recognized as a valid type.

**Comment by andymckay** [comment]
Developer Edition is now based off of Firefox Beta, please use Firefox Nightly instead.

**Comment by mgol** [comment]
See #16.
