### ISSUE TITLE
The Policy page documents Developer Edition can be used for experiments

### ISSUE THREAD

**Issue by mgol** [web-ext-experiments/about#16]
The page at https://webextensions-experiments.readthedocs.io/en/latest/policy.html#policy says:

> Currently Experiments can only be run on Firefox Nightly and Firefox Developer Edition.

Per https://github.com/web-ext-experiments/about/issues/14#issuecomment-307431180 this is no longer true, only Nightly can be used.

It'd be also worth checking if other parts of the site don't repeat the same incorrect information.

**Comment by caitmuenster** [comment]
Hi @mgol, sorry for the belated reply. Good news -- WebExtensions Experiments can be used on Firefox Developer Edition and Nightly! I'll update the documentation for consistency. :) 

https://wiki.mozilla.org/Add-ons/Firefox57
