### ISSUE TITLE
Support for latest Firefox Nightly

### ISSUE THREAD

**Issue by lukaszpolowczyk** [web-ext-experiments/about#17]
Is this project still supported? I can not install the experimental API in the latest Firefox Nightly.

**Comment by yfdyh000** [comment]
I see this issue. mozregression tell me this [regression range](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=45d8844f012430cd8826fdb18f1f11be76071b2d&tochange=c0b4c13955e71735654c4bf53186eca801e5e461) repeated...

**Comment by lukaszpolowczyk** [comment]
Will it be repaired?

**Comment by yfdyh000** [comment]
No news. Do you would fill a bug to [Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?product=Toolkit&component=WebExtensions%3A%20Experiments&resolution=---)?

**Comment by lukaszpolowczyk** [comment]
No. I would have liked someone else added, maybe you?

Such a message:
There was an error during installation: Add-on onwindows@experiments.addons.mozilla.org is not compatible with application version. add-on minVersion: 51.0. add-on maxVersion: *.

**Comment by yfdyh000** [comment]
filled https://bugzilla.mozilla.org/show_bug.cgi?id=1393571.

**Comment by lukaszpolowczyk** [comment]
Oh, again the new flag to include. :)

This site has gaps, even long unfinished texts. Eg for the scheme.json file.

**Comment by caitmuenster** [comment]
Sorry for the belated response to this issue. @yfdyh000, would you be open to submitting a PR to update https://webextensions-experiments.readthedocs.io/en/latest/how.html#installing-the-experiment with the information about setting the "extensions.legacy.enabled" preference to true?

**Comment by Happy-Ferret** [comment]
Hi @caitmuenster. 

I don't see ``extensions.legacy.enabled`` documented anywhere, yet this issue is closed.
Mind if I submit a PR for it? Provided @yfdyh000 is not already at it, of course.

**Comment by Rob--W** [comment]
Experiments can be loaded without any special flags since Firefox 59 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1394121 ).

**Comment by caitmuenster** [comment]
Thanks, @Rob--W! 

@Happy-Ferret, it also looks like some big changes to experiments are going to get a bit of a revamp soon. We will likely be holding off on updating the documentation until those changes land.

**Comment by aswan** [comment]
And the big changes aren't meant to be a secret, you can follow along at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1323845

But in short, you'll be able to bundle an experiment directly with the extension that uses it.  At the same time, experiments will look more like apis as they land in mozilla-central, so they'll be able to do things like include code that runs in a content process.

**Comment by Happy-Ferret** [comment]
Does that mean experiments will eventually be allowed to run on the Release channel, as well?

**Comment by aswan** [comment]
> Does that mean experiments will eventually be allowed to run on the Release channel, as well?

That isn't planned, no.  Experiments are a way to prototype new APIs, but if you have a new API that you'd like users to be able to use on release, getting the API landed directly in Firefox is the way to go.

**Comment by Happy-Ferret** [comment]
Oh. Good. That makes more sense.
Would've been odd to basically see legacy extensions return by another name (since one could then just write an API experiment that does all the same privileged operations traditional bootstrapped addons did and bundle them with a webextension).
