### ISSUE TITLE
Extending an existing API

### ISSUE THREAD

**Issue by Happy-Ferret** [web-ext-experiments/about#25]
Curious.

What if my experiment extends an existing API (``browser.cookies``, in my case)?
Will I be able to provide this as an API experiment to you or will I need to go through different channels?

Note: This is mostly a policy question. From a technological viewpoint, it seems to work just fine (I wrote the experiment earlier today, on behest of a coworker, but just want to make sure I get together all the proper documentation before I even attempt to have it uplifted).

**Comment by aswan** [comment]
We don't have any way for community-contributed experiments to be signed so there's not any policy..  If there's a change to something like `browser.cookies` that you'd like to propose, an experiment can be a useful way to prototype and demonstrate the change, but ultimately something like that would, if approved, land directly in mozilla-central.

**Comment by Happy-Ferret** [comment]
Oh. I understand it would be landing in mozilla-central directly.

My question is whether it makes sense to open up an issue for it on here.

**Comment by caitmuenster** [comment]
Hey @Happy-Ferret! You probably don't want to submit a PR for your experiment, but yes, please open a new issue on this repo. We'll ask the engineering team to review the experiment and ask you to come to an upcoming [design-decision-triage meeting](https://wiki.mozilla.org/WebExtensions/Triage#Purpose_of_Meeting) to check in about next steps.  

If the experiment is approved, we'll assign a mentor to help you uplift it to mozilla-central.

**Comment by Happy-Ferret** [comment]
Yea. Sorry. I accidentally wrote PR. Meant to say issue. I edited it.

Thanks. Will do this then. :)

**Comment by Happy-Ferret** [comment]
Well. Whatcha know.

The functionality my API experiment would've provided is already available with Nightly, under `` browser.privacy.websites.cookieConfig`` (I've written a small add-on using that functionality. [Cookies](https://addons.mozilla.org/en-US/firefox/addon/cookiesnew/))

I guess next time I'll need to check Bugzilla more thoroughly. 

Still. This thread was very informative. Thanks, everyone. 😺
