### ISSUE TITLE
My experiment API is undefined on Beta

### ISSUE THREAD

**Issue by leplatrem** [web-ext-experiments/about#29]
* Context:

I wrote a small addon to help the Firefox product-integrity team validate the Remote Settings feature. It basically exposes some Gecko internal stuff to the addon. 

* Where is your experiment located?
Code is here: https://github.com/leplatrem/remotesettings-pi/tree/v1.0.0/extension

* Can you provide a brief summary of what it does?

It exposes the `RemoteSettings.get()` and `RemoteSettings.onSync()` API available in Gecko 
https://firefox-source-docs.mozilla.org/services/common/services/RemoteSettings.html

* What's your issue?

It works like a charm on Nightly when I load it via `about:debugging`. 

On Beta, the `experiments.remotesettings` is undefined. 

> Note: the addon is not signed.

I would like to know why (I think @rpl told me already but I forgot). Maybe an entry in the FAQ would be helpful.

Thanks!!

**Comment by aswan** [comment]
On Nightly and Dev Edition, you can install unsigned experiments if you flip two preferences: `xpinstall.signatures.required` and `extensions.legacy.enabled`.  Unsigned experiments cannot be installed on beta or release regardless of any preference settings.
